# Generated by Django 3.1.7 on 2021-03-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('jobspec', models.TextField()),
            ],
        ),
    ]
